# version: 1.0.0
# Name as it appears on the Actions tab of GitHub (for current repo; this get's ignored if called from another repo)
name: 'Issue & PR Maintenance'

# Controls when the workflow will run
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - main
    paths:
      - .github/workflows/stale.yml
  schedule:
    - cron: '0 0 * * *'

jobs:
  stale:
    name: Shared Workflow
    permissions:
      issues: write
      pull-requests: write
    uses: sassy-bulldog/.github/.github/workflows/stale.yml@v0.3.0 # x-release-please-version
    secrets: inherit
